### ISSUE TITLE
Feature: add a change descriptionin changelog when bumping dependent packages / grouped packages

### ISSUE THREAD

**Issue by kenotron** [microsoft/beachball#252]
Currently, as part of a dependent package bump, nothing gets written as part of a changelog. This means that no changelog.json entry would be generated and therefore, subsequent tooling do not have a chance to look for why the version is bumped.

We should inject change entries into the "changes" key inside BumpInfo after the dependent and grouped bumping to ensure all changes are recorded.

**Comment by kate-hall** [comment]
+1 for this feature!

**Comment by willgorham** [comment]
Yes please :)

**Comment by imeldaloei** [comment]
YES PLEASE!!! this will help streamline the publishing of our release notes. we manage many different packages and are meticulous about making sure each version bump is documented. once this feature is implemented, we will be able to automate the publishing of our release notes. currently, it's copying and pasting for every single package 😃

**Comment by Netail** [comment]
@kenotron any update on this? Would love this too :)

**Comment by ecraig12345** [comment]
The feature of adding `Bump <name> to <x.y.z>` to the changelog for dependent bumps was added sometime after this issue was created. (I think that's what this issue referred to; it was just never closed for some reason.)

To roll up packages' changelogs to a single changelog, there's the option `changelog.groups`.

If you'd like some other variant of this behavior, please open a new issue.
