### ISSUE TITLE
Lockfile version not updated after publishing

### ISSUE THREAD

**Issue by mmaclach** [microsoft/beachball#482]
Steps to reproduce:

- Bump a package version
- Release package version

`package.json` version is updated, but `package-lock.json` still has the old version

Expected behavior:
`package-lock.json` version is also updated (or `yarn.lock`)

Right now, I can run install to update the lockfile, but it would be great if beachball could update the version change automatically.

**Comment by ecraig12345** [comment]
Can you provide more details about your repo setup? In the monorepo setups I'm familiar with, packages within the monorepo shouldn't typically be listed in the lock file.

**Comment by mmaclach** [comment]
Hi  @ecraig12345,

I'm using lerna and each package has its own lockfile.

For example, package-A has a version 1.0.0. When I publish a new version, using `beachball publish`, the `package.json` will be updated to the new version, but the lockfile version will not change.

For a workaround currently, I'm running `npm i --production --package-lock-only` in every package via lerna.

**Comment by ecraig12345** [comment]
Ah okay, I think most of the teams using beachball today are using yarn workspaces (one yarn.lock at the root, which doesn't include any references to local packages), so we didn't hit this issue. 

Since the appropriate post-publish command (and whether it's necessary) would vary between monorepo/package manager setups, I'm not sure it's something we ought to bake into beachball. 

However we do already have an option `hooks.prepublish` which you can specify in `beachball.config.js`. So it would be reasonable to add a similar `postpublish` hook.
https://github.com/microsoft/beachball/blob/2b1097b159d9ec63f6e607d2288187ec4393fbca/src/types/BeachballOptions.ts#L66-L74

This isn't something that any of the beachball maintainers will have time to add any time soon, but if you wanted to submit a PR we'd be happy to review it (should be pretty straightforward to implement using the pattern from the `prerelease` hook).

**Comment by mmaclach** [comment]
Hi @ecraig12345, 
that will work - I can make a PR with those changes.
Thanks!

**Comment by mmaclach** [comment]
https://github.com/microsoft/beachball/pull/486#issuecomment-773694879

**Comment by codyzu** [comment]
We got the `package-lock.json` file updating with npm workspaces here: https://github.com/microsoft/beachball/issues/525#issuecomment-1094622657
