### ISSUE TITLE
Feature Request: custom renderer for content before the markerComment

### ISSUE THREAD

**Issue by georgialoper** [microsoft/beachball#975]
Hello 👋

I would like to surface beachball's generated `CHANGELOG.md` file on my package's documentation site. However, I do not want to show the `This log was last generated on <DateTime> and should not be manually modified.` message to my consumers. Additionally, I would like to change the `<h1>` from `# Changelog - <@package-name>` to just `# @package-name`. 

It seems like this content is hardcoded in [renderContent.js](https://github.com/microsoft/beachball/blob/b3b46f6485318d2db483ae7fe3edfed954dd9754/src/changelog/renderChangelog.ts#L49), would you consider adding a `renderFrontmatter` or somesuch custom renderer to allow for more flexibility with this content?

**Comment by ecraig12345** [comment]
I think it would actually be okay to change the "last generated" part to a comment `<!-- This log was last generated ... -->` by default, since it's mostly intended for someone who's trying to edit the markdown source, and the date will be duplicated from the most recent changelog entry.

For custom rendering the h1, maybe that could be called `renderMainHeader` under `ChangelogOptions`?

**Comment by georgialoper** [comment]
@ecraig12345  both of those seem legit to me!
